[package]
name = "regulus"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.15.0"
slice-deque = "0.2.4"

[dev-dependencies]
approx = "0.3.2"
