[package]
name = "regulus"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.15.0"
circular-queue = "0.2.1"

[dev-dependencies]
approx = "0.3.2"
byteorder = "1.3"
dasp = { version = "0.11", features = ["signal"] }
tempfile = "3"
